--CREATE
CREATE TABLE Carro (id int generated by default as identity, placa varchar(50), cor varchar(50), portas int, motor float, isFlex varchar(10), combustivel varchar(50), PRIMARY KEY (id));

--INSERTS
INSERT INTO Carro (id,placa,cor,portas,motor,isFlex,combustivel) VALUES (1,'123abc','vermelho',4,1.0,true,'gasolina');
INSERT INTO Carro (id,placa,cor,portas,motor,isFlex,combustivel) values(2,'321cba','verde',2,1.5,true,'etanol');
INSERT INTO Carro (id,placa,cor,portas,motor,isFlex,combustivel) values(3,'456yui','amarelo',4,2.0,true,'alcool');

INSERT INTO Pessoa (id, nome, cpf, email) values (1, 'Samuel', '72635463542', 'samuel@email.com');
INSERT INTO Pessoa (id, nome, cpf, email) values (2, 'Alexandre', '98765243562', 'alexandre@email.com');